[package]
name = "rp-spi-tft"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = { workspace = true }
rp2040-hal = { workspace = true }
cortex-m = { workspace = true }
fugit = { workspace = true }

[features]
default = ["2d", "text"]
2d = []
text = []